#pragma once

#define MATRIX_COL_PINS { D3, D2, F4, F5, F6, F7, D4, C6 }
#define MATRIX_ROW_PINS { B1, B3, B2, B6, D7, E6, B4, B5 }

#define DIODE_DIRECTION COL2ROW

// #define DEBOUNCE 10

/* toggle layer */
// #define TAPPING_TOGGLE 2

/* mod tap */
#define TAPPING_TERM 175
#define QUICK_TAP_TERM 120

// #define IGNORE_MOD_TAP_INTERRUPT
// #define PERMISSIVE_HOLD
#define PERMISSIVE_HOLD_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define QUICK_TAP_TERM_PER_KEY

// #define CIRQUE_PINNACLE_TAP_ENABLE
#define POINTING_DEVICE_GESTURES_SCROLL_ENABLE
#define POINTING_DEVICE_TASK_THROTTLE_MS 2

// #define POINTING_DEVICE_ROTATION_270

// #define MOUSEKEY_DELAY 50
// #define MOUSEKEY_INTERVAL 16
// #define MOUSEKEY_MAX_SPEED 20
// #define MOUSEKEY_TIME_TO_MAX 20
// #define MOUSEKEY_INITIAL_SPEED 150
// #define MOUSEKEY_BASE_SPEED 2000
// #define MOUSEKEY_ACCELERATED_SPEED 10000

// #define PIMORONI_TRACKBALL_TIMEOUT 1000
// #define PIMORONI_TRACKBALL_SCALE 1

// #define MOUSE_EXTENDED_REPORT

// #define DEBOUNCE 20
// #define USB_POLLING_INTEVAL_MS 1
// #define QMK_KEYS_PER_SCAN 12

// #define COMBO_COUNT 1