#pragma once

#define MATRIX_COL_PINS { D3, D2, F4, F5, F6, F7, D4, C6 }
#define MATRIX_ROW_PINS { B2, B6, B5, B4, B1, B3, E6, D7 }

#define DIODE_DIRECTION COL2ROW

// #define DEBOUNCE 10

/* toggle layer */
// #define TAPPING_TOGGLE 2

/* mod tap */
#define TAPPING_TERM 175
#define QUICK_TAP_TERM 120

// #define IGNORE_MOD_TAP_INTERRUPT
// #define PERMISSIVE_HOLD
#define PERMISSIVE_HOLD_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define QUICK_TAP_TERM_PER_KEY

// #define CIRQUE_PINNACLE_TAP_ENABLE
// #define POINTING_DEVICE_GESTURES_SCROLL_ENABLE
#define POINTING_DEVICE_TASK_THROTTLE_MS 3

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 3

#define AUTO_MOUSE_TIME 1000