#pragma once

#define MATRIX_COL_PINS { D3, D2, F4, F5, D4, F6, C6, F7 }
#define MATRIX_ROW_PINS { B1, B3, B2, B6, D7, E6, B4, B5 }

#define DIODE_DIRECTION COL2ROW

/* toggle layer */
#define TAPPING_TOGGLE 2

/* mod tap */
#define TAPPING_TERM 175
#define IGNORE_MOD_TAP_INTERRUPT
// #define PERMISSIVE_HOLD
#define PERMISSIVE_HOLD_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY

// #define POINTING_DEVICE_ROTATION_270

// #define MOUSEKEY_DELAY 50
// #define MOUSEKEY_INTERVAL 16
// #define MOUSEKEY_MAX_SPEED 20
// #define MOUSEKEY_TIME_TO_MAX 20
// #define MOUSEKEY_INITIAL_SPEED 150
// #define MOUSEKEY_BASE_SPEED 2000
// #define MOUSEKEY_ACCELERATED_SPEED 10000

// #define PIMORONI_TRACKBALL_TIMEOUT 1000
// #define PIMORONI_TRACKBALL_SCALE 2

// #define MOUSE_EXTENDED_REPORT